sudo: required
services:
  - docker

before_install:
  - docker build -t stefanradudragomir/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true stefanradudragomir/docker-react npm run test


deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "Frontend"
  env: "Frontend-dev"
  bucket_name: "elasticbeanstalk-eu-north-1-891377062080"
  bucket_path: "Frontend"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"