sudo: required
services:
  - docker

before_install:
  - docker build -t stefanradudragomir/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true stefanradudragomir/docker-react npm run test
